import { library } from '@fortawesome/fontawesome-svg-core'
import { faGithub, faGoogle } from '@fortawesome/free-brands-svg-icons'
import {
    faArrowsRotate,
    faArrowRightFromBracket,
    faBell,
    faBrain,
    faCalendar,
    faChartPie,
    faChevronDown,
    faChevronRight,
    faCircleCheck,
    faCircleXmark,
    faCode,
    faCube,
    faDatabase,
    faFilter,
    faGear,
    faInfo,
    faLayerGroup,
    faPlus,
    faSort,
    faUser,
} from '@fortawesome/free-solid-svg-icons'

library.add(
    faArrowsRotate,
    faArrowRightFromBracket,
    faBell,
    faBrain,
    faCalendar,
    faChartPie,
    faChevronDown,
    faChevronRight,
    faCircleCheck,
    faCircleXmark,
    faCode,
    faCube,
    faDatabase,
    faFilter,
    faGear,
    faInfo,
    faLayerGroup,
    faPlus,
    faSort,
    faUser,
    faGithub,
    faGoogle
)
